// src/infrastructure/services/export/ExportService.js

const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');

class ExportService {
    /**
     * Generate a PDF report
     * @param {Object} data - The report data (summary, sales, etc.)
     * @param {string} title - Title of the report
     * @returns {Promise<Buffer>} PDF buffer
     */
    generatePDF(data, title) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const chunks = [];
                
                doc.on('data', (chunk) => chunks.push(chunk));
                doc.on('end', () => resolve(Buffer.concat(chunks)));
                doc.on('error', reject);

                // Header
                doc.fontSize(20).text('AI CFO ENTERPRISE', { align: 'center' });
                doc.moveDown();
                doc.fontSize(16).text(title, { align: 'center' });
                doc.moveDown();
                
                // Divider
                doc.strokeColor('#000000').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.moveDown();

                // Business Info
                doc.fontSize(12).text(`Business: ${data.businessName || 'N/A'}`);
                doc.text(`Date: ${new Date().toLocaleDateString('en-NG')}`);
                doc.moveDown();

                // Summary Section
                doc.fontSize(14).text('Executive Summary');
                doc.moveDown(0.5);
                
                const summary = data.summary || {};
                const metrics = [
                    { label: 'Total Revenue', value: `₦${(summary.totalRevenue || 0).toLocaleString()}` },
                    { label: 'Total Expenses', value: `₦${(summary.totalExpenses || 0).toLocaleString()}` },
                    { label: 'Net Profit', value: `₦${(summary.netProfit || 0).toLocaleString()}` },
                    { label: 'Total Sales', value: (summary.totalSales || 0).toString() },
                    { label: 'Active Debtors', value: (summary.activeDebtors || 0).toString() },
                    { label: 'Active Creditors', value: (summary.activeCreditors || 0).toString() },
                ];

                let yPos = doc.y;
                const col1X = 50;
                const col2X = 200;
                const col3X = 350;
                const col4X = 450;
                
                doc.fontSize(10);
                for (let i = 0; i < metrics.length; i += 2) {
                    const m1 = metrics[i];
                    const m2 = metrics[i + 1];
                    
                    doc.text(`${m1.label}:`, col1X, yPos);
                    doc.text(m1.value, col2X, yPos);
                    
                    if (m2) {
                        doc.text(`${m2.label}:`, col3X, yPos);
                        doc.text(m2.value, col4X, yPos);
                    }
                    
                    yPos += 20;
                }
                
                doc.moveDown();

                // Sales Section
                if (data.sales && data.sales.length > 0) {
                    doc.fontSize(14).text('Recent Sales');
                    doc.moveDown(0.5);
                    
                    doc.fontSize(10);
                    const startY = doc.y;
                    doc.text('Item', 50, startY);
                    doc.text('Qty', 200, startY);
                    doc.text('Price', 280, startY);
                    doc.text('Total', 380, startY);
                    doc.text('Customer', 450, startY);
                    
                    doc.moveDown();
                    let rowY = doc.y;
                    
                    for (const sale of data.sales.slice(0, 10)) {
                        doc.text(sale.item_name || 'N/A', 50, rowY);
                        doc.text((sale.quantity || 0).toString(), 200, rowY);
                        doc.text(`₦${(sale.unit_price || 0).toLocaleString()}`, 280, rowY);
                        doc.text(`₦${(sale.total_price || 0).toLocaleString()}`, 380, rowY);
                        doc.text(sale.customer_name || 'N/A', 450, rowY);
                        rowY += 20;
                    }
                }

                // Footer
                doc.moveDown(2);
                doc.fontSize(8).text('Generated by AI CFO ENTERPRISE', { align: 'center' });
                doc.text(`Generated on: ${new Date().toISOString()}`, { align: 'center' });
                
                doc.end();

            } catch (error) {
                reject(error);
            }
        });
    }

    /**
     * Generate an Excel report
     * @param {Object} data - The report data
     * @param {string} title - Title of the report
     * @returns {Promise<Buffer>} Excel buffer
     */
    async generateExcel(data, title) {
        try {
            const workbook = new ExcelJS.Workbook();
            workbook.creator = 'AI CFO ENTERPRISE';
            workbook.created = new Date();
            
            // Sheet 1: Summary
            const summarySheet = workbook.addWorksheet('Summary');
            
            // Title
            summarySheet.addRow(['AI CFO ENTERPRISE']);
            summarySheet.mergeCells('A1:D1');
            summarySheet.getRow(1).font = { size: 16, bold: true };
            summarySheet.addRow([title]);
            summarySheet.mergeCells('A2:D2');
            summarySheet.getRow(2).font = { size: 12, bold: true };
            summarySheet.addRow([]);

            // Business Info
            summarySheet.addRow(['Business:', data.businessName || 'N/A']);
            summarySheet.addRow(['Date:', new Date().toLocaleDateString('en-NG')]);
            summarySheet.addRow([]);

            // Metrics
            const summary = data.summary || {};
            const metrics = [
                ['Metric', 'Value'],
                ['Total Revenue', `₦${(summary.totalRevenue || 0).toLocaleString()}`],
                ['Total Expenses', `₦${(summary.totalExpenses || 0).toLocaleString()}`],
                ['Net Profit', `₦${(summary.netProfit || 0).toLocaleString()}`],
                ['Total Sales', (summary.totalSales || 0).toString()],
                ['Active Debtors', (summary.activeDebtors || 0).toString()],
                ['Active Creditors', (summary.activeCreditors || 0).toString()],
            ];
            
            metrics.forEach(row => summarySheet.addRow(row));
            
            // Style the metrics table
            summarySheet.getRow(4).font = { bold: true };

            // Sheet 2: Sales
            const salesSheet = workbook.addWorksheet('Sales');
            salesSheet.addRow(['Item', 'Quantity', 'Unit Price', 'Total', 'Customer', 'Date']);
            salesSheet.getRow(1).font = { bold: true };
            
            if (data.sales && data.sales.length > 0) {
                for (const sale of data.sales) {
                    salesSheet.addRow([
                        sale.item_name || 'N/A',
                        sale.quantity || 0,
                        `₦${(sale.unit_price || 0).toLocaleString()}`,
                        `₦${(sale.total_price || 0).toLocaleString()}`,
                        sale.customer_name || 'N/A',
                        new Date(sale.sale_date).toLocaleDateString('en-NG'),
                    ]);
                }
            }

            // Auto-size columns
            salesSheet.columns.forEach(col => {
                col.width = 15;
            });

            const buffer = await workbook.xlsx.writeBuffer();
            return buffer;

        } catch (error) {
            throw error;
        }
    }
}

module.exports = ExportService;