-- 021_fix_telegram_id_type.sql
-- v1.0.0 — Align users.telegram_id type across environments.
--
-- Background: production's users.telegram_id was manually changed from
-- bigint to text at some point (to support web_-prefixed IDs generated by
-- the registration flow). That change was never captured in a migration,
-- so freshly-migrated databases (like staging) still have bigint and
-- reject the web_... strings with:
--   invalid input syntax for type bigint: "web_..."
--
-- This migration changes the column to text IF it isn't already text.
-- Safe on prod (no-op), fixes staging, correct on future fresh DBs.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'users'
       AND column_name = 'telegram_id'
       AND data_type <> 'text'
  ) THEN
    -- Drop the dependent indexes first (Postgres can't alter a column
    -- that's referenced by a unique constraint without dropping it).
    ALTER TABLE users DROP CONSTRAINT IF EXISTS users_telegram_id_key;
    DROP INDEX IF EXISTS idx_users_telegram_id;

    -- Change the column type. USING telegram_id::text casts any existing
    -- bigint values to strings (there are none in staging, but this makes
    -- the migration safe if data ever exists).
    ALTER TABLE users
      ALTER COLUMN telegram_id TYPE text USING telegram_id::text;

    -- Recreate the constraint and index.
    ALTER TABLE users
      ADD CONSTRAINT users_telegram_id_key UNIQUE (telegram_id);
    CREATE INDEX IF NOT EXISTS idx_users_telegram_id
      ON users (telegram_id);

    RAISE NOTICE '021: users.telegram_id changed to text';
  ELSE
    RAISE NOTICE '021: users.telegram_id is already text — nothing to do';
  END IF;
END $$;