// src/config/industryConfig.js
import { 
  Store, Wrench, Building, Stethoscope, Briefcase, 
  Home as HomeIcon, GraduationCap, Truck as TruckIcon,
  TrendingUp, TrendingDown, DollarSign, ShoppingCart, 
  Package, Users, CreditCard, Building2, BarChart3,
  FileText, Calendar, Brain, Layers, Lightbulb, Settings
} from 'lucide-react';

export const INDUSTRY_CONFIGS = {
  'RETAIL': {
    label: 'Retail / Wholesale',
    icon: Store,
    iconColor: 'text-blue-600 dark:text-blue-400',
    bgColor: 'bg-blue-50 dark:bg-blue-900/30',
    borderColor: 'border-blue-200 dark:border-blue-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'sales', label: 'Sales', icon: ShoppingCart, color: 'blue' },
      { key: 'inventory', label: 'Inventory Value', icon: Package, color: 'teal' },
      { key: 'debtors', label: 'Debtors', icon: Users, color: 'yellow' },
    ],
    quickActions: [
      { label: 'Record Sale', icon: ShoppingCart, href: '/sales/record' },
      { label: 'Add Stock', icon: Package, href: '/inventory/add' },
      { label: 'Record Payment', icon: Users, href: '/debtors/pay' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Sales', 'Inventory', 'Debtors', 'Creditors', 'Customers', 'Suppliers', 'Reports'],
    sidebar: [
      { icon: TrendingUp, label: 'Sales', href: '/sales' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: ShoppingCart, label: 'Purchases', href: '/purchases' },
      { icon: Package, label: 'Inventory', href: '/inventory' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: Building2, label: 'Customers', href: '/customers' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'MANUFACTURING': {
    label: 'Manufacturing',
    icon: Wrench,
    iconColor: 'text-orange-600 dark:text-orange-400',
    bgColor: 'bg-orange-50 dark:bg-orange-900/30',
    borderColor: 'border-orange-200 dark:border-orange-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'production', label: 'Production Runs', icon: TrendingUp, color: 'orange' },
      { key: 'raw_materials', label: 'Raw Materials', icon: Package, color: 'teal' },
      { key: 'debtors', label: 'Debtors', icon: Users, color: 'yellow' },
    ],
    quickActions: [
      { label: 'Record Sale', icon: ShoppingCart, href: '/sales/record' },
      { label: 'Add Raw Material', icon: Package, href: '/inventory/add' },
      { label: 'Start Production', icon: Wrench, href: '/production/start' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Sales', 'Raw Materials', 'Production', 'Inventory', 'Suppliers', 'Reports'],
    sidebar: [
      { icon: TrendingUp, label: 'Sales', href: '/sales' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: ShoppingCart, label: 'Purchases', href: '/purchases' },
      { icon: Package, label: 'Raw Materials', href: '/inventory?type=raw' },
      { icon: Package, label: 'Inventory', href: '/inventory' },
      { icon: Wrench, label: 'Production', href: '/production' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'CONSTRUCTION': {
    label: 'Construction',
    icon: Building,
    iconColor: 'text-amber-600 dark:text-amber-400',
    bgColor: 'bg-amber-50 dark:bg-amber-900/30',
    borderColor: 'border-amber-200 dark:border-amber-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'projects', label: 'Active Projects', icon: Briefcase, color: 'amber' },
      { key: 'materials', label: 'Materials', icon: Package, color: 'teal' },
      { key: 'debtors', label: 'Debtors', icon: Users, color: 'yellow' },
    ],
    quickActions: [
      { label: 'Record Sale', icon: ShoppingCart, href: '/sales/record' },
      { label: 'Add Materials', icon: Package, href: '/inventory/add' },
      { label: 'Create Project', icon: Briefcase, href: '/projects/create' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Projects', 'Materials', 'Project Billing', 'Suppliers', 'Reports'],
    sidebar: [
      { icon: Building, label: 'Projects', href: '/projects' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: Package, label: 'Materials', href: '/inventory' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'HEALTHCARE': {
    label: 'Healthcare',
    icon: Stethoscope,
    iconColor: 'text-red-600 dark:text-red-400',
    bgColor: 'bg-red-50 dark:bg-red-900/30',
    borderColor: 'border-red-200 dark:border-red-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'patients', label: 'Patients', icon: Users, color: 'red' },
      { key: 'visits', label: 'Visits', icon: TrendingUp, color: 'blue' },
      { key: 'inventory', label: 'Supplies', icon: Package, color: 'teal' },
    ],
    quickActions: [
      { label: 'Record Visit', icon: Stethoscope, href: '/visits/record' },
      { label: 'Add Patient', icon: Users, href: '/patients/add' },
      { label: 'Record Payment', icon: Users, href: '/debtors/pay' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Patient Visits', 'Medical Supplies', 'Patients', 'Billing', 'Reports'],
    sidebar: [
      { icon: Stethoscope, label: 'Visits', href: '/visits' },
      { icon: Users, label: 'Patients', href: '/patients' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: Package, label: 'Supplies', href: '/inventory' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'CONSULTANCY': {
    label: 'Consultancy',
    icon: Briefcase,
    iconColor: 'text-purple-600 dark:text-purple-400',
    bgColor: 'bg-purple-50 dark:bg-purple-900/30',
    borderColor: 'border-purple-200 dark:border-purple-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'clients', label: 'Clients', icon: Users, color: 'purple' },
      { key: 'hours', label: 'Billable Hours', icon: TrendingUp, color: 'blue' },
      { key: 'projects', label: 'Projects', icon: Briefcase, color: 'amber' },
    ],
    quickActions: [
      { label: 'Record Hour', icon: Briefcase, href: '/hours/record' },
      { label: 'Add Client', icon: Users, href: '/clients/add' },
      { label: 'Create Project', icon: Briefcase, href: '/projects/create' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Clients', 'Billable Hours', 'Projects', 'Invoices', 'Reports'],
    sidebar: [
      { icon: Briefcase, label: 'Projects', href: '/projects' },
      { icon: Users, label: 'Clients', href: '/clients' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: BarChart3, label: 'Hours', href: '/hours' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'REAL_ESTATE': {
    label: 'Real Estate',
    icon: HomeIcon,
    iconColor: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-900/30',
    borderColor: 'border-emerald-200 dark:border-emerald-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'properties', label: 'Properties', icon: HomeIcon, color: 'emerald' },
      { key: 'tenants', label: 'Tenants', icon: Users, color: 'purple' },
      { key: 'rent', label: 'Rent Collected', icon: TrendingUp, color: 'blue' },
    ],
    quickActions: [
      { label: 'Add Property', icon: HomeIcon, href: '/properties/add' },
      { label: 'Add Tenant', icon: Users, href: '/tenants/add' },
      { label: 'Record Rent', icon: DollarSign, href: '/rent/record' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Properties', 'Tenants', 'Rent Collection', 'Maintenance', 'Reports'],
    sidebar: [
      { icon: HomeIcon, label: 'Properties', href: '/properties' },
      { icon: Users, label: 'Tenants', href: '/tenants' },
      { icon: DollarSign, label: 'Rent', href: '/rent' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      { icon: TruckIcon, label: 'Suppliers', href: '/suppliers' },
    ],
  },
  'EDUCATION': {
    label: 'Education',
    icon: GraduationCap,
    iconColor: 'text-indigo-600 dark:text-indigo-400',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/30',
    borderColor: 'border-indigo-200 dark:border-indigo-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'students', label: 'Students', icon: Users, color: 'indigo' },
      { key: 'classes', label: 'Classes', icon: TrendingUp, color: 'blue' },
      { key: 'fees', label: 'Fees', icon: DollarSign, color: 'yellow' },
    ],
    quickActions: [
      { label: 'Add Student', icon: Users, href: '/students/add' },
      { label: 'Record Fee', icon: DollarSign, href: '/fees/record' },
      { label: 'Create Class', icon: GraduationCap, href: '/classes/create' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Students', 'Classes', 'School Fees', 'Exams', 'Reports'],
    sidebar: [
      { icon: Users, label: 'Students', href: '/students' },
      { icon: GraduationCap, label: 'Classes', href: '/classes' },
      { icon: DollarSign, label: 'Fees', href: '/fees' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      { icon: CreditCard, label: 'Creditors', href: '/creditors' },
      // ❌ REMOVED: Suppliers
    ],
  },
  'LOGISTICS': {
    label: 'Logistics',
    icon: TruckIcon,
    iconColor: 'text-cyan-600 dark:text-cyan-400',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/30',
    borderColor: 'border-cyan-200 dark:border-cyan-800',
    stats: [
      { key: 'revenue', label: 'Revenue', icon: DollarSign, color: 'primary' },
      { key: 'trips', label: 'Trips', icon: TrendingUp, color: 'cyan' },
      { key: 'vehicles', label: 'Vehicles', icon: TruckIcon, color: 'blue' },
      { key: 'drivers', label: 'Drivers', icon: Users, color: 'purple' },
    ],
    quickActions: [
      { label: 'Record Trip', icon: TruckIcon, href: '/trips/record' },
      { label: 'Add Vehicle', icon: TruckIcon, href: '/vehicles/add' },
      { label: 'Add Driver', icon: Users, href: '/drivers/add' },
      { label: 'View Reports', icon: FileText, href: '/reports/daily' },
    ],
    features: ['Vehicles', 'Drivers', 'Trips', 'Trip Revenue', 'Reports'],
    sidebar: [
      { icon: TruckIcon, label: 'Trips', href: '/trips' },
      { icon: TruckIcon, label: 'Vehicles', href: '/vehicles' },
      { icon: Users, label: 'Drivers', href: '/drivers' },
      { icon: DollarSign, label: 'Income', href: '/income' },
      { icon: TrendingDown, label: 'Expenses', href: '/expenses' },
      { icon: Users, label: 'Debtors', href: '/debtors' },
      // ❌ REMOVED: Creditors
      // ❌ REMOVED: Suppliers
    ],
  },
};

export const COMMON_NAV_ITEMS = [
  { icon: BarChart3, label: 'Reports', href: '/reports' },
  { icon: Calendar, label: 'Forecast', href: '/forecast' },
  { icon: Lightbulb, label: 'Recommendations', href: '/recommendations' },
  { icon: Brain, label: 'AI Assistant', href: '/ai' },
  { icon: Layers, label: 'Subscription', href: '/subscription' },
  { icon: Settings, label: 'Settings', href: '/settings' },
];

export const STAT_COLORS = {
  primary: 'bg-primary-50 dark:bg-primary-900/30 text-primary-600 dark:text-gold-400',
  blue: 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400',
  red: 'bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400',
  orange: 'bg-orange-50 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400',
  yellow: 'bg-yellow-50 dark:bg-yellow-900/30 text-yellow-600 dark:text-yellow-400',
  purple: 'bg-purple-50 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400',
  teal: 'bg-teal-50 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400',
  amber: 'bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400',
  emerald: 'bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400',
  indigo: 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400',
  cyan: 'bg-cyan-50 dark:bg-cyan-900/30 text-cyan-600 dark:text-cyan-400',
};