// src/config/plans.js

module.exports = {
    free: {
        id: 'free',
        name: 'Free',
        description: 'Basic plan for small businesses',
        price: 0,
        features: {
            sales: true,
            income: true,
            expenses: true,
            purchases: true,
            inventory: true,
            debtors: true,
            creditors: true,
            customers: true,
            suppliers: true,
            projects: true,
            reports: true,
            forecasting: true,
            ai_insights: true,
            multi_user: false,
            support: false,
        },
        limits: {
            transactions: 100,
            users: 1,
        },
    },
    pro: {
        id: 'pro',
        name: 'Pro',
        description: 'Professional plan for growing businesses',
        price: 5000,
        features: {
            sales: true,
            income: true,
            expenses: true,
            purchases: true,
            inventory: true,
            debtors: true,
            creditors: true,
            customers: true,
            suppliers: true,
            projects: true,
            reports: true,
            forecasting: true,
            ai_insights: true,
            multi_user: true,
            support: true,
        },
        limits: {
            transactions: 1000,
            users: 5,
        },
    },
    business: {
        id: 'business',
        name: 'Business',
        description: 'Enterprise plan for large businesses',
        price: 15000,
        features: {
            sales: true,
            income: true,
            expenses: true,
            purchases: true,
            inventory: true,
            debtors: true,
            creditors: true,
            customers: true,
            suppliers: true,
            projects: true,
            reports: true,
            forecasting: true,
            ai_insights: true,
            multi_user: true,
            support: true,
        },
        limits: {
            transactions: 10000,
            users: 20,
        },
    },
};