'use strict';

/**
 * Decision Engine Contracts
 * Single source of truth for enums, constants, and validation.
 * @version 1.2.0-prod
 */

const deepFreeze = (obj) => {
  if (obj === null || typeof obj !== 'object' || Object.isFrozen(obj)) return obj;
  Object.getOwnPropertyNames(obj).forEach((prop) => {
    const v = obj[prop];
    if (v && typeof v === 'object') deepFreeze(v);
  });
  return Object.freeze(obj);
};

const DECISION_TYPES = deepFreeze({
  // Cash Flow
  CASH_FLOW_WARNING: 'CASH_FLOW_WARNING',
  CASH_TREND_DECLINE: 'CASH_TREND_DECLINE',
  CASH_SHORTAGE_PROJECTION: 'CASH_SHORTAGE_PROJECTION',
  NEGATIVE_CASH_FLOW: 'NEGATIVE_CASH_FLOW',
  DISCRETIONARY_SPENDING_REVIEW: 'DISCRETIONARY_SPENDING_REVIEW',
  COLLECTION_ACCELERATION: 'COLLECTION_ACCELERATION',
  SUPPLIER_PAYMENT_REVIEW: 'SUPPLIER_PAYMENT_REVIEW',
  CASH_CONCENTRATION_RISK: 'CASH_CONCENTRATION_RISK',
  CASH_BUFFER_EROSION: 'CASH_BUFFER_EROSION',
  INVESTMENT_OPPORTUNITY: 'INVESTMENT_OPPORTUNITY',
  // Inventory
  LOW_STOCK: 'LOW_STOCK',
  STOCK_OUT_RISK: 'STOCK_OUT_RISK',
  EXCESS_INVENTORY: 'EXCESS_INVENTORY',
  SLOW_MOVING_INVENTORY: 'SLOW_MOVING_INVENTORY',
  HIGH_VALUE_INVENTORY_RISK: 'HIGH_VALUE_INVENTORY_RISK',
  DETERIORATING_INVENTORY: 'DETERIORATING_INVENTORY',
  INVENTORY_CONCENTRATION: 'INVENTORY_CONCENTRATION',
  SEASONAL_STOCK_READINESS: 'SEASONAL_STOCK_READINESS',
  INVENTORY_SHRINKAGE: 'INVENTORY_SHRINKAGE',
  REPLENISHMENT_OPPORTUNITY: 'REPLENISHMENT_OPPORTUNITY',
  // Pricing & Profitability
  MARGIN_COMPRESSION: 'MARGIN_COMPRESSION',
  BELOW_TARGET_MARGIN: 'BELOW_TARGET_MARGIN',
  PRICE_BELOW_COST: 'PRICE_BELOW_COST',
  GROSS_MARGIN_DECLINE: 'GROSS_MARGIN_DECLINE',
  NET_PROFIT_DECLINE: 'NET_PROFIT_DECLINE',
  REVENUE_GROWTH_PROFIT_DECLINE: 'REVENUE_GROWTH_PROFIT_DECLINE',
  PRODUCT_PROFITABILITY_ALERT: 'PRODUCT_PROFITABILITY_ALERT',
  PRICE_INCREASE_OPPORTUNITY: 'PRICE_INCREASE_OPPORTUNITY',
  DISCOUNT_EFFECTIVENESS: 'DISCOUNT_EFFECTIVENESS',
  PRICE_SENSITIVITY_ALERT: 'PRICE_SENSITIVITY_ALERT',
  // Receivables & Payables
  OVERDUE_RECEIVABLES: 'OVERDUE_RECEIVABLES',
  CRITICAL_OVERDUE: 'CRITICAL_OVERDUE',
  CUSTOMER_COLLECTION_PRIORITY: 'CUSTOMER_COLLECTION_PRIORITY',
  AR_AGING_CONCENTRATION: 'AR_AGING_CONCENTRATION',
  CUSTOMER_CREDIT_RISK: 'CUSTOMER_CREDIT_RISK',
  SUPPLIER_PAYMENT_OVERDUE: 'SUPPLIER_PAYMENT_OVERDUE',
  SUPPLIER_PAYMENT_URGENCY: 'SUPPLIER_PAYMENT_URGENCY',
  PAYABLE_NEGOTIATION_OPPORTUNITY: 'PAYABLE_NEGOTIATION_OPPORTUNITY',
  SUPPLIER_CONCENTRATION_RISK: 'SUPPLIER_CONCENTRATION_RISK',
  PAYABLE_OPTIMIZATION: 'PAYABLE_OPTIMIZATION',
  // Expenses
  EXPENSE_GROWTH_ALERT: 'EXPENSE_GROWTH_ALERT',
  EXPENSE_ANOMALY: 'EXPENSE_ANOMALY',
  EXPENSE_CONCENTRATION: 'EXPENSE_CONCENTRATION',
  ADVERTISING_EFFICIENCY: 'ADVERTISING_EFFICIENCY',
  RENT_LEASE_REVIEW: 'RENT_LEASE_REVIEW',
  SALARY_COST_REVIEW: 'SALARY_COST_REVIEW',
  DISCRETIONARY_EXPENSE_REVIEW: 'DISCRETIONARY_EXPENSE_REVIEW',
  COST_CONTROL_OPPORTUNITY: 'COST_CONTROL_OPPORTUNITY',
  FIXED_COST_WARNING: 'FIXED_COST_WARNING',
  VARIABLE_COST_OPTIMIZATION: 'VARIABLE_COST_OPTIMIZATION',
  // Customers & Suppliers
  CUSTOMER_CONCENTRATION_RISK: 'CUSTOMER_CONCENTRATION_RISK',
  TOP_5_CONCENTRATION: 'TOP_5_CONCENTRATION',
  CUSTOMER_REVENUE_DECLINE: 'CUSTOMER_REVENUE_DECLINE',
  HIGH_VALUE_CUSTOMER_RETENTION: 'HIGH_VALUE_CUSTOMER_RETENTION',
  CUSTOMER_CHURN_RISK: 'CUSTOMER_CHURN_RISK',
  CUSTOMER_ACQUISITION_OPPORTUNITY: 'CUSTOMER_ACQUISITION_OPPORTUNITY',
  SUPPLIER_COST_INCREASE: 'SUPPLIER_COST_INCREASE',
  SUPPLIER_PAYMENT_NEGOTIATION: 'SUPPLIER_PAYMENT_NEGOTIATION',
  SUPPLIER_DIVERSIFICATION: 'SUPPLIER_DIVERSIFICATION',
  // Growth & Working Capital
  REVENUE_GROWTH_OPPORTUNITY: 'REVENUE_GROWTH_OPPORTUNITY',
  PRODUCT_GROWTH_LEADER: 'PRODUCT_GROWTH_LEADER',
  MARGIN_IMPROVEMENT_OPPORTUNITY: 'MARGIN_IMPROVEMENT_OPPORTUNITY',
  MARKET_EXPANSION_SIGNAL: 'MARKET_EXPANSION_SIGNAL',
  WORKING_CAPITAL_PRESSURE: 'WORKING_CAPITAL_PRESSURE',
  WORKING_CAPITAL_OPTIMIZATION: 'WORKING_CAPITAL_OPTIMIZATION',
  CASH_CONVERSION_CYCLE_LENGTHENING: 'CASH_CONVERSION_CYCLE_LENGTHENING',
  LIQUIDITY_RISK: 'LIQUIDITY_RISK',
  QUICK_RATIO_WARNING: 'QUICK_RATIO_WARNING',
  OPERATING_LEVERAGE_RISK: 'OPERATING_LEVERAGE_RISK',
});

const DECISION_CATEGORIES = deepFreeze({
  CASH_FLOW: 'CASH_FLOW',
  INVENTORY: 'INVENTORY',
  PRICING: 'PRICING',
  PROFITABILITY: 'PROFITABILITY',
  RECEIVABLES: 'RECEIVABLES',
  PAYABLES: 'PAYABLES',
  EXPENSES: 'EXPENSES',
  CUSTOMERS: 'CUSTOMERS',
  SUPPLIERS: 'SUPPLIERS',
  GROWTH: 'GROWTH',
  WORKING_CAPITAL: 'WORKING_CAPITAL',
});

const DECISION_PRIORITY = deepFreeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
});

const DECISION_SEVERITY = deepFreeze({
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  INFO: 'INFO',
  OPPORTUNITY: 'OPPORTUNITY',
});

const DECISION_STATUS = deepFreeze({
  ACTIVE: 'ACTIVE',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  ACTIONED: 'ACTIONED',
  DISMISSED: 'DISMISSED',
  RESOLVED: 'RESOLVED',
  EXPIRED: 'EXPIRED',
});

const DECISION_TIMEFRAME = deepFreeze({
  IMMEDIATE: 'IMMEDIATE',
  SHORT_TERM: 'SHORT_TERM',
  MEDIUM_TERM: 'MEDIUM_TERM',
  LONG_TERM: 'LONG_TERM',
});

const DECISION_ENTITY = deepFreeze({
  BUSINESS: 'BUSINESS',
  PRODUCT: 'PRODUCT',
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER',
  PROJECT: 'PROJECT',
  EMPLOYEE: 'EMPLOYEE',
});

const PRIORITY_ORDER = deepFreeze({
  [DECISION_PRIORITY.CRITICAL]: 0,
  [DECISION_PRIORITY.HIGH]: 1,
  [DECISION_PRIORITY.MEDIUM]: 2,
  [DECISION_PRIORITY.LOW]: 3,
});

const PRIORITY_EXPIRY_DAYS = deepFreeze({
  [DECISION_PRIORITY.CRITICAL]: 3,
  [DECISION_PRIORITY.HIGH]: 7,
  [DECISION_PRIORITY.MEDIUM]: 14,
  [DECISION_PRIORITY.LOW]: 30,
});

const PRIORITY_EMOJI = deepFreeze({
  [DECISION_PRIORITY.CRITICAL]: '🔴',
  [DECISION_PRIORITY.HIGH]: '🟠',
  [DECISION_PRIORITY.MEDIUM]: '🟡',
  [DECISION_PRIORITY.LOW]: '🟢',
});

const SEVERITY_EMOJI = deepFreeze({
  [DECISION_SEVERITY.CRITICAL]: '🚨',
  [DECISION_SEVERITY.WARNING]: '⚠️',
  [DECISION_SEVERITY.INFO]: 'ℹ️',
  [DECISION_SEVERITY.OPPORTUNITY]: '💡',
});

const DECISION_TYPES_ARRAY = Object.freeze(Object.values(DECISION_TYPES));
const DECISION_CATEGORIES_ARRAY = Object.freeze(Object.values(DECISION_CATEGORIES));
const DECISION_PRIORITY_ARRAY = Object.freeze(Object.values(DECISION_PRIORITY));
const DECISION_SEVERITY_ARRAY = Object.freeze(Object.values(DECISION_SEVERITY));
const DECISION_STATUS_ARRAY = Object.freeze(Object.values(DECISION_STATUS));
const DECISION_TIMEFRAME_ARRAY = Object.freeze(Object.values(DECISION_TIMEFRAME));
const DECISION_ENTITY_ARRAY = Object.freeze(Object.values(DECISION_ENTITY));

const ACTIVE_STATUSES = Object.freeze([
  DECISION_STATUS.ACTIVE,
  DECISION_STATUS.ACKNOWLEDGED,
]);

const Validators = deepFreeze({
  isValidType: (type) => DECISION_TYPES_ARRAY.includes(type),
  isValidCategory: (category) => DECISION_CATEGORIES_ARRAY.includes(category),
  isValidPriority: (priority) => DECISION_PRIORITY_ARRAY.includes(priority),
  isValidSeverity: (severity) => DECISION_SEVERITY_ARRAY.includes(severity),
  isValidStatus: (status) => DECISION_STATUS_ARRAY.includes(status),
  isValidTimeframe: (timeframe) => DECISION_TIMEFRAME_ARRAY.includes(timeframe),
  isValidEntity: (entity) => DECISION_ENTITY_ARRAY.includes(entity),
  isValidConfidence: (confidence) =>
    typeof confidence === 'number' && Number.isFinite(confidence) && confidence >= 0 && confidence <= 100,
  isActiveStatus: (status) => ACTIVE_STATUSES.includes(status),
});

module.exports = {
  DECISION_TYPES,
  DECISION_CATEGORIES,
  DECISION_PRIORITY,
  DECISION_SEVERITY,
  DECISION_STATUS,
  DECISION_TIMEFRAME,
  DECISION_ENTITY,
  PRIORITY_ORDER,
  PRIORITY_EXPIRY_DAYS,
  PRIORITY_EMOJI,
  SEVERITY_EMOJI,
  ACTIVE_STATUSES,
  Validators,
  DECISION_TYPES_ARRAY,
  DECISION_CATEGORIES_ARRAY,
  DECISION_PRIORITY_ARRAY,
  DECISION_SEVERITY_ARRAY,
  DECISION_STATUS_ARRAY,
  DECISION_TIMEFRAME_ARRAY,
  DECISION_ENTITY_ARRAY,
};