const {
  DECISION_TYPES,
  DECISION_CATEGORIES,
  DECISION_PRIORITY,
  DECISION_SEVERITY,
  DECISION_STATUS,
  DECISION_TIMEFRAME,
  DECISION_ENTITY,
  PRIORITY_ORDER,
  PRIORITY_EXPIRY_DAYS,
  PRIORITY_EMOJI,
  SEVERITY_EMOJI
} = require('../../../src/application/services/decision/contracts/DecisionContracts');

describe('Decision Contracts', () => {
  describe('DECISION_TYPES', () => {
    it('should have all cash flow types', () => {
      expect(DECISION_TYPES.CASH_FLOW_WARNING).toBe('CASH_FLOW_WARNING');
      expect(DECISION_TYPES.CASH_TREND_DECLINE).toBe('CASH_TREND_DECLINE');
      expect(DECISION_TYPES.CASH_SHORTAGE_PROJECTION).toBe('CASH_SHORTAGE_PROJECTION');
      expect(DECISION_TYPES.NEGATIVE_CASH_FLOW).toBe('NEGATIVE_CASH_FLOW');
      expect(DECISION_TYPES.DISCRETIONARY_SPENDING_REVIEW).toBe('DISCRETIONARY_SPENDING_REVIEW');
      expect(DECISION_TYPES.COLLECTION_ACCELERATION).toBe('COLLECTION_ACCELERATION');
      expect(DECISION_TYPES.SUPPLIER_PAYMENT_REVIEW).toBe('SUPPLIER_PAYMENT_REVIEW');
      expect(DECISION_TYPES.CASH_CONCENTRATION_RISK).toBe('CASH_CONCENTRATION_RISK');
      expect(DECISION_TYPES.CASH_BUFFER_EROSION).toBe('CASH_BUFFER_EROSION');
      expect(DECISION_TYPES.INVESTMENT_OPPORTUNITY).toBe('INVESTMENT_OPPORTUNITY');
    });

    it('should have all inventory types', () => {
      expect(DECISION_TYPES.LOW_STOCK).toBe('LOW_STOCK');
      expect(DECISION_TYPES.STOCK_OUT_RISK).toBe('STOCK_OUT_RISK');
      expect(DECISION_TYPES.EXCESS_INVENTORY).toBe('EXCESS_INVENTORY');
      expect(DECISION_TYPES.SLOW_MOVING_INVENTORY).toBe('SLOW_MOVING_INVENTORY');
      expect(DECISION_TYPES.HIGH_VALUE_INVENTORY_RISK).toBe('HIGH_VALUE_INVENTORY_RISK');
      expect(DECISION_TYPES.DETERIORATING_INVENTORY).toBe('DETERIORATING_INVENTORY');
      expect(DECISION_TYPES.INVENTORY_CONCENTRATION).toBe('INVENTORY_CONCENTRATION');
      expect(DECISION_TYPES.SEASONAL_STOCK_READINESS).toBe('SEASONAL_STOCK_READINESS');
      expect(DECISION_TYPES.INVENTORY_SHRINKAGE).toBe('INVENTORY_SHRINKAGE');
      expect(DECISION_TYPES.REPLENISHMENT_OPPORTUNITY).toBe('REPLENISHMENT_OPPORTUNITY');
    });

    it('should have all pricing and profitability types', () => {
      expect(DECISION_TYPES.MARGIN_COMPRESSION).toBe('MARGIN_COMPRESSION');
      expect(DECISION_TYPES.BELOW_TARGET_MARGIN).toBe('BELOW_TARGET_MARGIN');
      expect(DECISION_TYPES.PRICE_BELOW_COST).toBe('PRICE_BELOW_COST');
      expect(DECISION_TYPES.GROSS_MARGIN_DECLINE).toBe('GROSS_MARGIN_DECLINE');
      expect(DECISION_TYPES.NET_PROFIT_DECLINE).toBe('NET_PROFIT_DECLINE');
      expect(DECISION_TYPES.REVENUE_GROWTH_PROFIT_DECLINE).toBe('REVENUE_GROWTH_PROFIT_DECLINE');
      expect(DECISION_TYPES.PRODUCT_PROFITABILITY_ALERT).toBe('PRODUCT_PROFITABILITY_ALERT');
      expect(DECISION_TYPES.PRICE_INCREASE_OPPORTUNITY).toBe('PRICE_INCREASE_OPPORTUNITY');
      expect(DECISION_TYPES.DISCOUNT_EFFECTIVENESS).toBe('DISCOUNT_EFFECTIVENESS');
      expect(DECISION_TYPES.PRICE_SENSITIVITY_ALERT).toBe('PRICE_SENSITIVITY_ALERT');
    });

    it('should have all receivable and payable types', () => {
      expect(DECISION_TYPES.OVERDUE_RECEIVABLES).toBe('OVERDUE_RECEIVABLES');
      expect(DECISION_TYPES.CRITICAL_OVERDUE).toBe('CRITICAL_OVERDUE');
      expect(DECISION_TYPES.CUSTOMER_COLLECTION_PRIORITY).toBe('CUSTOMER_COLLECTION_PRIORITY');
      expect(DECISION_TYPES.AR_AGING_CONCENTRATION).toBe('AR_AGING_CONCENTRATION');
      expect(DECISION_TYPES.CUSTOMER_CREDIT_RISK).toBe('CUSTOMER_CREDIT_RISK');
      expect(DECISION_TYPES.SUPPLIER_PAYMENT_OVERDUE).toBe('SUPPLIER_PAYMENT_OVERDUE');
      expect(DECISION_TYPES.SUPPLIER_PAYMENT_URGENCY).toBe('SUPPLIER_PAYMENT_URGENCY');
      expect(DECISION_TYPES.PAYABLE_NEGOTIATION_OPPORTUNITY).toBe('PAYABLE_NEGOTIATION_OPPORTUNITY');
      expect(DECISION_TYPES.SUPPLIER_CONCENTRATION_RISK).toBe('SUPPLIER_CONCENTRATION_RISK');
      expect(DECISION_TYPES.PAYABLE_OPTIMIZATION).toBe('PAYABLE_OPTIMIZATION');
    });

    it('should have all expense types', () => {
      expect(DECISION_TYPES.EXPENSE_GROWTH_ALERT).toBe('EXPENSE_GROWTH_ALERT');
      expect(DECISION_TYPES.EXPENSE_ANOMALY).toBe('EXPENSE_ANOMALY');
      expect(DECISION_TYPES.EXPENSE_CONCENTRATION).toBe('EXPENSE_CONCENTRATION');
      expect(DECISION_TYPES.ADVERTISING_EFFICIENCY).toBe('ADVERTISING_EFFICIENCY');
      expect(DECISION_TYPES.RENT_LEASE_REVIEW).toBe('RENT_LEASE_REVIEW');
      expect(DECISION_TYPES.SALARY_COST_REVIEW).toBe('SALARY_COST_REVIEW');
      expect(DECISION_TYPES.DISCRETIONARY_EXPENSE_REVIEW).toBe('DISCRETIONARY_EXPENSE_REVIEW');
      expect(DECISION_TYPES.COST_CONTROL_OPPORTUNITY).toBe('COST_CONTROL_OPPORTUNITY');
      expect(DECISION_TYPES.FIXED_COST_WARNING).toBe('FIXED_COST_WARNING');
      expect(DECISION_TYPES.VARIABLE_COST_OPTIMIZATION).toBe('VARIABLE_COST_OPTIMIZATION');
    });
  });

  describe('DECISION_CATEGORIES', () => {
    it('should have all categories', () => {
      expect(DECISION_CATEGORIES.CASH_FLOW).toBe('CASH_FLOW');
      expect(DECISION_CATEGORIES.INVENTORY).toBe('INVENTORY');
      expect(DECISION_CATEGORIES.PRICING).toBe('PRICING');
      expect(DECISION_CATEGORIES.PROFITABILITY).toBe('PROFITABILITY');
      expect(DECISION_CATEGORIES.RECEIVABLES).toBe('RECEIVABLES');
      expect(DECISION_CATEGORIES.PAYABLES).toBe('PAYABLES');
      expect(DECISION_CATEGORIES.EXPENSES).toBe('EXPENSES');
      expect(DECISION_CATEGORIES.CUSTOMERS).toBe('CUSTOMERS');
      expect(DECISION_CATEGORIES.SUPPLIERS).toBe('SUPPLIERS');
      expect(DECISION_CATEGORIES.GROWTH).toBe('GROWTH');
      expect(DECISION_CATEGORIES.WORKING_CAPITAL).toBe('WORKING_CAPITAL');
    });
  });

  describe('DECISION_PRIORITY', () => {
    it('should have all priority levels', () => {
      expect(DECISION_PRIORITY.CRITICAL).toBe('CRITICAL');
      expect(DECISION_PRIORITY.HIGH).toBe('HIGH');
      expect(DECISION_PRIORITY.MEDIUM).toBe('MEDIUM');
      expect(DECISION_PRIORITY.LOW).toBe('LOW');
    });
  });

  describe('DECISION_SEVERITY', () => {
    it('should have all severity levels', () => {
      expect(DECISION_SEVERITY.CRITICAL).toBe('CRITICAL');
      expect(DECISION_SEVERITY.WARNING).toBe('WARNING');
      expect(DECISION_SEVERITY.INFO).toBe('INFO');
      expect(DECISION_SEVERITY.OPPORTUNITY).toBe('OPPORTUNITY');
    });
  });

  describe('DECISION_STATUS', () => {
    it('should have all status values', () => {
      expect(DECISION_STATUS.ACTIVE).toBe('ACTIVE');
      expect(DECISION_STATUS.ACKNOWLEDGED).toBe('ACKNOWLEDGED');
      expect(DECISION_STATUS.ACTIONED).toBe('ACTIONED');
      expect(DECISION_STATUS.DISMISSED).toBe('DISMISSED');
      expect(DECISION_STATUS.RESOLVED).toBe('RESOLVED');
      expect(DECISION_STATUS.EXPIRED).toBe('EXPIRED');
    });
  });

  describe('DECISION_TIMEFRAME', () => {
    it('should have all timeframe values', () => {
      expect(DECISION_TIMEFRAME.IMMEDIATE).toBe('IMMEDIATE');
      expect(DECISION_TIMEFRAME.SHORT_TERM).toBe('SHORT_TERM');
      expect(DECISION_TIMEFRAME.MEDIUM_TERM).toBe('MEDIUM_TERM');
      expect(DECISION_TIMEFRAME.LONG_TERM).toBe('LONG_TERM');
    });
  });

  describe('DECISION_ENTITY', () => {
    it('should have all entity types', () => {
      expect(DECISION_ENTITY.BUSINESS).toBe('BUSINESS');
      expect(DECISION_ENTITY.PRODUCT).toBe('PRODUCT');
      expect(DECISION_ENTITY.CUSTOMER).toBe('CUSTOMER');
      expect(DECISION_ENTITY.SUPPLIER).toBe('SUPPLIER');
      expect(DECISION_ENTITY.PROJECT).toBe('PROJECT');
      expect(DECISION_ENTITY.EMPLOYEE).toBe('EMPLOYEE');
    });
  });

  describe('PRIORITY_ORDER', () => {
    it('should order priorities correctly', () => {
      expect(PRIORITY_ORDER.CRITICAL).toBe(0);
      expect(PRIORITY_ORDER.HIGH).toBe(1);
      expect(PRIORITY_ORDER.MEDIUM).toBe(2);
      expect(PRIORITY_ORDER.LOW).toBe(3);
    });
  });

  describe('PRIORITY_EXPIRY_DAYS', () => {
    it('should have correct expiry days', () => {
      expect(PRIORITY_EXPIRY_DAYS.CRITICAL).toBe(3);
      expect(PRIORITY_EXPIRY_DAYS.HIGH).toBe(7);
      expect(PRIORITY_EXPIRY_DAYS.MEDIUM).toBe(14);
      expect(PRIORITY_EXPIRY_DAYS.LOW).toBe(30);
    });
  });

  describe('PRIORITY_EMOJI', () => {
    it('should have emojis for each priority', () => {
      expect(PRIORITY_EMOJI.CRITICAL).toBe('🔴');
      expect(PRIORITY_EMOJI.HIGH).toBe('🟠');
      expect(PRIORITY_EMOJI.MEDIUM).toBe('🟡');
      expect(PRIORITY_EMOJI.LOW).toBe('🟢');
    });
  });

  describe('SEVERITY_EMOJI', () => {
    it('should have emojis for each severity', () => {
      expect(SEVERITY_EMOJI.CRITICAL).toBe('🚨');
      expect(SEVERITY_EMOJI.WARNING).toBe('⚠️');
      expect(SEVERITY_EMOJI.INFO).toBe('ℹ️');
      expect(SEVERITY_EMOJI.OPPORTUNITY).toBe('💡');
    });
  });
});